# Generated by Django 5.1.4 on 2025-02-05 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to='materials/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materials',
            },
        ),
        migrations.CreateModel(
            name='QuestionPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_code', models.CharField(max_length=10, unique=True)),
                ('paper_title', models.CharField(max_length=255)),
                ('paper_description', models.TextField(blank=True, null=True)),
                ('time_limit', models.PositiveIntegerField(help_text='Time limit in minutes')),
                ('no_of_qs', models.PositiveIntegerField(blank=True, null=True)),
                ('total_marks', models.PositiveIntegerField(blank=True, null=True)),
                ('is_practice_paper', models.BooleanField(default=False)),
                ('is_assessment_paper', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Question Paper',
                'verbose_name_plural': 'Question Papers',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('mark', models.PositiveIntegerField(default=1)),
                ('option_A', models.CharField(max_length=255)),
                ('option_B', models.CharField(max_length=255)),
                ('option_C', models.CharField(max_length=255)),
                ('option_D', models.CharField(max_length=255)),
                ('correct_option', models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], default='A', help_text='Key of the correct option for MCQs.', max_length=1)),
                ('question_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='aptitude_app.questionpaper')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='StudentResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_code', models.CharField(default='', max_length=10)),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('attended', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Malpractice', 'Malpractice')], default='Completed', max_length=20)),
                ('date_of_exam', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Result',
                'verbose_name_plural': 'Student Results',
            },
        ),
    ]
