# Generated by Django 5.1.4 on 2025-01-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptitude_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'ordering': ['batch_year'], 'verbose_name_plural': 'Batches'},
        ),
        migrations.RemoveConstraint(
            model_name='batch',
            name='unique_batch_year',
        ),
        migrations.AddField(
            model_name='batch',
            name='department',
            field=models.CharField(choices=[('ECE', 'Electronics and Communication Engineering'), ('CSE', 'Computer Science Engineering'), ('MECH', 'Mechanical Engineering'), ('EEE', 'Electrical and Electronics Engineering'), ('CIVIL', 'Civil Engineering'), ('IT', 'Information Technology')], default='ECE', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.UniqueConstraint(fields=('batch_year', 'department'), name='unique_batch_year_department'),
        ),
    ]
