# Generated by Django 5.1.4 on 2025-02-05 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptitude_app', '0002_extra'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signup_option', models.BooleanField(default=False)),
                ('about_us', models.TextField(default='Velammal', max_length=10000)),
            ],
        ),
        migrations.DeleteModel(
            name='extra',
        ),
    ]
