# Generated by Django 5.1.4 on 2025-02-09 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptitude_app', '0004_studentresults_test_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='placement_stories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('package', models.CharField(max_length=255)),
                ('content', models.TextField(max_length=10000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='placement_stories/')),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Placement Story',
                'verbose_name_plural': 'Placement Stories',
            },
        ),
        migrations.RemoveField(
            model_name='material',
            name='description',
        ),
    ]
