# Generated by Django 5.1.4 on 2025-01-19 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptitude_app', '0004_alter_batch_year_alter_result_test_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_code', models.CharField(default='adf9', editable=False, max_length=4, unique=True)),
                ('paper_title', models.CharField(max_length=255)),
                ('paper_description', models.TextField(blank=True, null=True)),
                ('time_limit', models.PositiveIntegerField(help_text='Time limit in minutes')),
                ('total_marks', models.PositiveIntegerField(default=0)),
                ('is_practice_paper', models.BooleanField(default=False)),
                ('is_assessment_paper', models.BooleanField(default=False)),
                ('question_type', models.CharField(choices=[('MCQ', 'Multiple Choice'), ('FILL', 'Filling the Blanks')], max_length=4)),
            ],
            options={
                'verbose_name': 'Question Paper',
                'verbose_name_plural': 'Question Papers',
            },
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='section',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(blank=True, null=True)),
                ('question_image', models.ImageField(blank=True, null=True, upload_to='questions/')),
                ('mark', models.PositiveIntegerField(default=1)),
                ('options', models.JSONField(blank=True, help_text="JSON format: {'1': 'Option A', '2': 'Option B', ...}", null=True)),
                ('correct_option', models.CharField(blank=True, help_text="Key of the correct option for MCQs (e.g., '1').", max_length=1, null=True)),
                ('correct_answer', models.CharField(blank=True, max_length=255, null=True)),
                ('question_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='aptitude_app.questionpaper')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
    ]
