# Generated by Django 5.1.4 on 2025-02-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptitude_app', '0005_placement_stories_remove_material_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='placement_stories',
            field=models.BooleanField(default=False),
        ),
    ]
