# Generated by Django 5.1.4 on 2025-02-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptitude_app', '0005_placement_stories_remove_material_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionpaper',
            name='is_assessment_paper',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='is_practice_paper',
            field=models.BooleanField(default=True),
        ),
    ]
