# Generated by Django 5.1.4 on 2025-01-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptitude_app', '0006_rename_correct_answer_question_option_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='option_1',
            new_name='option_A',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='option_2',
            new_name='option_B',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='option_3',
            new_name='option_C',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='option_4',
            new_name='option_D',
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_option',
            field=models.CharField(blank=True, choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], help_text='Key of the correct option for MCQs.', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='paper_code',
            field=models.CharField(default='1f2e', editable=False, max_length=4, unique=True),
        ),
    ]
