# Generated by Django 5.1.4 on 2025-02-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptitude_app', '0007_remove_globalsettings_placement_stories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsettings',
            name='about_us',
            field=models.TextField(default='Platform designed to help students enhance their skills and prepare for success.', max_length=10000),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='notice_board',
            field=models.TextField(default='Evaluate and sharpen your logical, numerical, and verbal reasoning abilities.', max_length=10000),
        ),
        migrations.AlterField(
            model_name='placement_stories',
            name='image',
            field=models.ImageField(blank=True, default='images/Vcet_logo.png', null=True, upload_to='placement_stories/'),
        ),
    ]
