# Generated by Django 5.1.4 on 2025-01-19 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptitude_app', '0007_rename_option_1_question_option_a_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionpaper',
            name='paper_code',
            field=models.CharField(default='3380', editable=False, max_length=4, unique=True),
        ),
    ]
