# Generated by Django 5.1.4 on 2025-02-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptitude_app', '0008_alter_globalsettings_about_us_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placement_stories',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='placement_stories/'),
        ),
    ]
