# Generated by Django 5.1.4 on 2025-01-19 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptitude_app', '0008_alter_questionpaper_paper_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpaper',
            name='number_of_questions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='paper_code',
            field=models.CharField(default='4965', editable=False, max_length=4, unique=True),
        ),
    ]
