# Generated by Django 5.1.4 on 2025-01-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptitude_app', '0009_questionpaper_number_of_questions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_paper',
        ),
        migrations.RemoveField(
            model_name='questionpaper',
            name='number_of_questions',
        ),
        migrations.AddField(
            model_name='question',
            name='question_papers',
            field=models.ManyToManyField(related_name='questions', to='aptitude_app.questionpaper'),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='paper_code',
            field=models.CharField(default='60e2', editable=False, max_length=4, unique=True),
        ),
    ]
