# Generated by Django 5.1.4 on 2025-02-11 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aptitude_app', '0006_alter_questionpaper_is_assessment_paper_and_more'),
        ('aptitude_app', '0009_alter_placement_stories_image'),
    ]

    operations = [
    ]
