# Generated by Django 5.1.4 on 2025-01-19 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptitude_app', '0010_remove_question_question_paper_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_papers',
        ),
        migrations.AddField(
            model_name='question',
            name='question_paper',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='aptitude_app.questionpaper'),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='paper_code',
            field=models.CharField(default='ebd2', editable=False, max_length=4, unique=True),
        ),
    ]
