# Generated by Django 5.1.4 on 2025-03-03 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aptitude_app', '0010_merge_20250211_2327'),
        ('aptitude_app', '0011_alter_globalsettings_about_us'),
    ]

    operations = [
    ]
