# Generated by Django 5.1.4 on 2025-03-03 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptitude_app', '0012_merge_20250303_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='option_A',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_B',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_C',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_D',
            field=models.TextField(),
        ),
    ]
