# Generated by Django 5.1.4 on 2025-01-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresults',
            name='test_title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
