# Generated by Django 5.1.4 on 2025-01-29 15:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_studentresults_test_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresults',
            name='percentage',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
