# Generated by Django 5.1.4 on 2025-02-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_studentresults_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='batch_year',
            field=models.IntegerField(default=2026, null=True),
        ),
    ]
