# Generated by Django 5.1.4 on 2025-02-08 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_user_batch_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='geeksforgeeksID',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='hackerEarthID',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='hackerrankID',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='leetcodeID',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
