# Generated by Django 5.1.4 on 2025-02-08 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_user_geeksforgeeksid_user_hackerearthid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_problems_solved',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
