# Generated by Django 5.1.4 on 2025-02-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_user_total_problems_solved'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='university_number',
            field=models.IntegerField(null=True),
        ),
    ]
