# Generated by Django 5.1.4 on 2025-02-08 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_user_university_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='geeksforgeeksID',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hackerEarthID',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hackerrankID',
        ),
        migrations.RemoveField(
            model_name='user',
            name='leetcodeID',
        ),
        migrations.RemoveField(
            model_name='user',
            name='total_problems_solved',
        ),
    ]
